-- SQL script to create the 'staff' table

CREATE TABLE IF NOT EXISTS staff (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  role VARCHAR(60) NOT NULL DEFAULT 'Staff',
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  sales_today INT DEFAULT 0,
  products_added INT DEFAULT 0,
  joined_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;